apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  storageClassName: nfs-client #Precisa da instalação do provisionador NFS
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
